### ISSUE TITLE
God bless you - where do I make start the App

### ISSUE THREAD

**Issue by DavideDessi319** [danReynolds/warmup_routine#2]
First of all thank you for saving us all and making it so easy.

I have a question, I'm using your example to test the Open Container and returning the rest of my app inside the "onComplete" function, but I'm still seeing the blue container overlaying on top of my app. I'm sure that the problem is on my end and I'm doing something wrong. I know that you're making a new example so I'll wait for that and see if I can find my error there or I'll wait for your answer if you'll respond.

Anyway thank you so much again, you're saving us from many struggles

**Comment by danReynolds** [comment]
Ah got it. The `onComplete` is not a builder function, I'll make that clearer. I'm doing something like:

```
if (shouldShowOverlay) {
  return WarmupOverlay(
    placeholderBuilder: (context) {
      return Container(
        color: Colors.white,
      );
    },
    builder: (context) {
      return Container(
        color: Colors.white,
      );
    },
    onComplete: () {
      setState(() {
        shouldShowOverlay = false;
      });
    },
    animations: [
      WarmupAnimation(
        repeat: 2,
        builder: (context, complete) {
          return WarmupLottieAnimations(
            onComplete: () {
              complete();
            },
          );
        },
      )
    ],
  );
} else {
  return MyApp();
}
```

in my app, so hopefully that works for you.
